import Head from 'next/head';
import Vedio from './Vedio';

export default function About() {
  return (
    <div>
      <div className="container mx-auto p-4">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 text-center mt-8 ">
          <div className="flex flex-col items-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-2">15K</h1>
            <p className="text-gray-600 text-lg">Happy Customers</p>
          </div>
          <div className="flex flex-col items-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-2">150K</h1>
            <p className="text-gray-600 text-lg">Monthly Visitors</p>
          </div>
          <div className="flex flex-col items-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-2">15</h1>
            <p className="text-gray-600 text-lg">Countries Worldwide</p>
          </div>
          <div className="flex flex-col items-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-2">100+</h1>
            <p className="text-gray-600 text-lg">Top Partners</p>
          </div>
        </main>
      </div>
      <Vedio />
    </div>
  );
}
